<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <AssemblyName>ZE2.ModLoader</AssemblyName>
    <RootNamespace>ZE2.ModLoader</RootNamespace>
    <PlatformTarget>x86</PlatformTarget>
    <Prefer32Bit>true</Prefer32Bit>
    <NoWarn>$(NoWarn);0162</NoWarn>
    <GameRoot Condition="'$(GameRoot)' == ''">..\..\..\ze2_bepinexVersion\Zombie Estate 2</GameRoot>
    <XnaGacRoot>C:\Windows\Microsoft.NET\assembly\GAC_32</XnaGacRoot>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="BepInEx.Core">
      <HintPath>..\..\dist\overlay\BepInEx\core\BepInEx.Core.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="BepInEx.NET.Common">
      <HintPath>..\..\dist\overlay\BepInEx\core\BepInEx.NET.Common.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="0Harmony">
      <HintPath>..\..\dist\overlay\BepInEx\core\0Harmony.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Zombie Estate 2">
      <HintPath>$(GameRoot)\Zombie Estate 2.real.exe</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Microsoft.Xna.Framework">
      <HintPath>$(XnaGacRoot)\Microsoft.Xna.Framework\v4.0_4.0.0.0__842cf8be1de50553\Microsoft.Xna.Framework.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Microsoft.Xna.Framework.Game">
      <HintPath>$(XnaGacRoot)\Microsoft.Xna.Framework.Game\v4.0_4.0.0.0__842cf8be1de50553\Microsoft.Xna.Framework.Game.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Microsoft.Xna.Framework.Graphics">
      <HintPath>$(XnaGacRoot)\Microsoft.Xna.Framework.Graphics\v4.0_4.0.0.0__842cf8be1de50553\Microsoft.Xna.Framework.Graphics.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="System.Drawing" />
    <Reference Include="System.Xml" />
    <Reference Include="System.Xml.Linq" />
  </ItemGroup>
</Project>
